'use client';
import {ArrowDownRight,ArrowUpRight,ScanLine,ShieldCheck} from 'lucide-react';
import {num,decimal} from './api';
export function ResultsOverview({data,onSelect}:{data:any,onSelect:(compound:string)=>void}){
 const candidates=data.candidates; const top=candidates.slice(0,6); const maximum=Math.max(.001,...top.map((c:any)=>Math.abs(c.score)));
 const up=data.summary.up_genes,down=data.summary.down_genes,total=up+down; const significant=candidates.filter((c:any)=>c.permutation_fdr!==null&&c.permutation_fdr<.05).length;
 return <div className="overview-grid"><section className="panel leader-panel"><div className="panel-heading"><div><span className="eyebrow">COMPUTATIONAL PREDICTIONS</span><h2>Leading reversal candidates</h2></div><ArrowDownRight size={21}/></div><div className="leader-chart">{top.map((c:any,i:number)=><button onClick={()=>onSelect(c.compound)} className="leader-row" key={c.compound}><span className="leader-index">0{i+1}</span><span className="leader-name">{c.compound}</span><span className="leader-track"><span style={{width:Math.abs(c.score)/maximum*100+'%',background:c.score<0?undefined:'var(--up)'}}/></span><span className="leader-score">{decimal(c.score)}</span><ArrowUpRight size={13}/></button>)}</div><div className="chart-footnote"><span><i className="legend-dot"/>Negative scores indicate reversal</span><span>Median across contexts</span></div></section><section className="panel signature-overview"><div className="panel-heading"><div><span className="eyebrow">CALCULATED SIGNATURE</span><h2>Two directions. One signature.</h2></div><ScanLine size={20}/></div><div className="signature-visual"><svg viewBox="0 0 120 120" role="img" aria-label={`${up} upregulated and ${down} downregulated genes`}><circle cx="60" cy="60" r="48" fill="none" stroke="var(--down)" strokeWidth="8"/><circle cx="60" cy="60" r="48" fill="none" stroke="var(--up)" strokeWidth="8" strokeDasharray={`${total?up/total*301.59:0} 301.59`} transform="rotate(-90 60 60)"/><text x="60" y="58" textAnchor="middle" fill="var(--text)" fontSize="27">{num(total)}</text><text x="60" y="75" textAnchor="middle" fill="var(--muted)" fontSize="8" letterSpacing="1.2">GENES SELECTED</text></svg><div className="signature-legend"><div><span><i style={{background:'var(--up)'}}/>Upregulated</span><strong className="up">{num(up)} <ArrowUpRight size={14}/></strong></div><div><span><i style={{background:'var(--down)'}}/>Downregulated</span><strong className="down">{num(down)} <ArrowDownRight size={14}/></strong></div></div></div><div className="coverage-note"><ShieldCheck size={16}/><span><strong>{num(data.summary.mapped_signature_genes)}</strong> genes mapped to the LINCS universe</span></div></section><div className="evidence-banner"><ShieldCheck size={18}/><div><strong>Hypothesis generation, with the uncertainty in view.</strong><span>{num(significant)} of {num(candidates.length)} compounds have exploratory permutation BH-adjusted p &lt; 0.05. Examine robustness and validation before interpreting a rank.</span></div><span className="pill">RESEARCH USE ONLY</span></div></div>
}
export function SignatureSchematic(){return <div className="schematic"><div className="schematic-heading"><span><i className="dot"/>THE REVERSAL PRINCIPLE</span><span>01 — 03</span></div><div className="schematic-labels"><span>CANCER SIGNATURE</span><span>DRUG RESPONSE</span></div><svg viewBox="0 0 430 240" role="img" aria-label="Illustration of opposing cancer and drug expression directions, not experimental data"><defs><pattern id="dots" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#384237"/></pattern></defs><rect width="430" height="240" fill="url(#dots)"/>{[50,120,190].map((y,i)=><g key={y}><path d={`M60 ${y} C150 ${y},150 ${240-y},215 ${240-y} S300 ${y},370 ${y}`} stroke={i===1?'#a3c2d5':'#c3e8a4'} strokeWidth="1.5" fill="none" opacity=".5"/><circle cx="60" cy={y} r="16" fill="#20281f" stroke={i===1?'#a3c2d5':'#c3e8a4'}/><circle cx="370" cy={y} r="16" fill="#20281f" stroke={i===1?'#c3e8a4':'#a3c2d5'}/><text x="60" y={y+5} textAnchor="middle" fontSize="18" fill={i===1?'#a3c2d5':'#c3e8a4'}>{i===1?'↓':'↑'}</text><text x="370" y={y+5} textAnchor="middle" fontSize="18" fill={i===1?'#c3e8a4':'#a3c2d5'}>{i===1?'↑':'↓'}</text></g>)}<circle cx="215" cy="120" r="32" fill="#161d17" stroke="#536548"/><path d="M201 113h27m-6-6 6 6-6 6M229 127h-27m6-6-6 6 6 6" stroke="#c3e8a4" fill="none" strokeWidth="1.4"/></svg><div className="schematic-bottom"><span>Opposing directions.<br/><strong>A starting point for investigation.</strong></span><span className="schematic-symbol">↗</span></div><p>Conceptual illustration · not experimental data</p></div>}
