'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {ArrowUpRight,BookOpen,FlaskConical,LayoutGrid,Layers3,Plus,ShieldCheck} from 'lucide-react';
import {api} from './api';
export function Header(){
 const path=usePathname(); const[runs,setRuns]=useState<any[]>([]);
 useEffect(()=>{let active=true;const refresh=()=>api<any[]>('/analyses').then(r=>{if(active)setRuns(r.slice(0,4))}).catch(()=>{});refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[path]);
 const links=[{href:'/',label:'Workspace',icon:LayoutGrid},{href:'/research',label:'Research notebook',icon:Layers3},{href:'/methodology',label:'Methodology',icon:BookOpen},{href:'/about',label:'About the platform',icon:FlaskConical}];
 return <><aside className="sidebar"><Link href="/" className="brand" aria-label="IRIS home"><i className="logo"/><span>iris<span className="brand-period">.</span></span></Link><div className="brand-caption">MOLECULAR DISCOVERY</div><Link href="/" className="new-analysis"><Plus size={15}/> New analysis <span>↗</span></Link><div className="nav-label">RESEARCH WORKSPACE</div><nav>{links.map(({href,label,icon:Icon})=><Link key={href} className={(path===href||(href==='/'&&path.startsWith('/analysis')))?'active':''} href={href}><Icon size={17} strokeWidth={1.5}/>{label}{path===href&&<i/>}</Link>)}</nav><div className="sidebar-runs"><div className="nav-label">RECENT ANALYSES <span>{runs.length.toString().padStart(2,'0')}</span></div>{runs.map(r=><Link href={'/analysis/'+r.id} className={'sidebar-run '+(path.endsWith(r.id)?'selected':'')} key={r.id}><span className={'run-dot '+r.status}/><div><strong>{r.project?.project_id||r.cancer}</strong><small>{r.id.slice(0,8)} <span>· {r.status.replace('_',' ')}</span></small></div></Link>)}{!runs.length&&<p className="small">Your analyses will appear here.</p>}</div><div className="sidebar-bottom"><ShieldCheck size={19}/><div>Evidence before interpretation.<p>Public data. Transparent methods.</p></div></div><Link href="/methodology" className="sidebar-version">EXPLORATORY RESEARCH <span>v0.1 <ArrowUpRight size={12}/></span></Link></aside><header className="topbar"><div className="topbar-title"><span className="mobile-brand">iris.</span><span className="desktop-label">Research workspace</span><span className="topbar-slash">/</span><span>{path.startsWith('/analysis')?'Analysis report':path.startsWith('/candidate')?'Compound evidence':path==='/research'?'Research notebook':path==='/methodology'?'Methodology':path==='/about'?'About':'Overview'}</span></div><div className="topbar-right"><span className="local-label"><i/>Local workspace</span><Link href="/methodology">Methods & sources <ArrowUpRight size={13}/></Link></div><nav className="mobile-nav"><Link href="/">Workspace</Link><Link href="/research">Research</Link><Link href="/methodology">Methods</Link></nav></header></>
}
export function Footer(){return <footer className="footer"><div><span className="footer-mark">iris.</span><span>Built for discovery. Grounded in evidence.</span></div><p>Computational hypotheses only. Prioritization does not establish therapeutic efficacy, safety, or patient benefit.</p><span className="footer-version">TCGA × LINCS / v0.1.0</span></footer>}
